name: invest_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: packages/common
  shared_components:
    path: packages/shared_components
  auth_service:
    path: packages/auth_service

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - packages/common/assets/images/
  #   - images/a_dot_ham.jpeg

  # example:
fonts:
    - family: SF Pro Text
      fonts:
        - asset: common/assets/font/SF Pro Text/SFProText-Regular.ttf
        - asset: common/assets/font/SF Pro Text/SFProText-Bold.ttf
          weight: 700
        - asset: common/assets/font/SF Pro Text/SFProText-Semibold.ttf
          weight: 600
        - asset: common/assets/font/SF Pro Text/SFProText-Medium.ttf
          weight: 500
  